### ISSUE TITLE
TDR timeout

### ISSUE THREAD

**Issue by quadpixels** [cjohnson57/OrdererTest#1]
https://github.com/cjohnson57/OrdererTest/blob/ff0a0447d6ff1b438d37c4a6a857f4d677b72f4c/kernel.cu#L170

I guess this line hit the [TDR timeout](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/timeout-detection-and-recovery) because this loop make the kernel take more than a few seconds to complete. I had seen this in some other program where its kernel ran for a long time (that program is a lot of GPU threads contending over an atomic counter.)
The TDR timeout on my system seemed to be around 2s according to my measurements, same as described in the linked page. I had just came to know about this a few days ago while porting some CUDA code from Linux to Windows (I wasn't able to install a CUDA driver newer than version 395 in Xubuntu on this laptop and setting up optirun and bumblebee wasn't very straightforward, that's why I'm porting that program to Windows.)

On Linux the TDR timeout was 5 seconds when the GPU running CUDA is driving the main display, if I remember correctly, and it could be circumvented by stopping the GUI desktop (log in over ssh).

This TDR timeout was somewhat unexpected, since on my laptop the dGPU is not driving the display, and if I run a long-running CUDA program using optirun in Linux the limit would not kick in. Apparently this is not the same on Windows but I believe there should also be a way to disable this limit --- I can use that program to test.

**Comment by cjohnson57** [comment]
That makes sense why the issue is happening. I found this Stackoverflow that suggests you can disable the TDR timeout using nsight: https://stackoverflow.com/questions/497685/cuda-apps-time-out-fail-after-several-seconds-how-to-work-around-this

>The easiest way to disable TDR for Cuda programming, assuming you have the NVIDIA Nsight tools installed, is to open the Nsight Monitor, click on "Nsight Monitor options", and under "General" set "WDDM TDR enabled" to false. This will change the registry setting for you. Close and reboot. Any change to the TDR registry setting won't take effect until you reboot.

I'm currently at work but will try disabling it when I get home

**Comment by cjohnson57** [comment]
The issue seems to persist in the same way after disabling the TDR timeout

**Comment by quadpixels** [comment]
Yeah, I wouldn't expect it to fix the program automatically, as there might still not be enough kernels running concurrently to for the current design to work.

I feel the number of concurrent kernels might be a limiting factor and tried to find if there's another answer to the original question: "How does the CPU notify a running kernel something happened", in addition to running multiple kernels.

One test using concurrent copy and kernel launch (just 1 kernel launch) is here: [host](https://github.com/quadpixels/GeauldenTigerTM/blob/master/geauldenTigerTM.cu#L168) [kernel](https://github.com/quadpixels/GeauldenTigerTM/blob/master/pingpong.cu#L20)

It looks there are a few traps in doing it this way:
- Writes to a memory allocated with `cudaHostAlloc` from the host may not be visible to the GPU immediately; they become visible to the GPU after a `cudaMemcpyAsync` is executed against some nearby address.
- Print statements form the kernel may be buffered; may appear to be "batched together" due to divergence & reconvergence, so printing may not be as a good indicator for showing what happens at what time, compared to storing stuff in arrays.

**Comment by quadpixels** [comment]
I modified the `OrderedGPU` kernel in a way such that individual GPU threads may be awakened by the CPU, and was able to get make further progress (in [this commit](https://github.com/quadpixels/OrdererTest/commit/89a351ba259880829053df3749bcefd6b1113e9f)) 
```
Index: 1, MsgNum: 0, BatchFull: 0
Index: 0, MsgNum: 0, BatchFull: 0
Index: 4, MsgNum: 0, BatchFull: 0
Index: 6, MsgNum: 2, BatchFull: 0
Index: 3, MsgNum: 2, BatchFull: 0
Index: 5, MsgNum: 2, BatchFull: 0
Index: 7, MsgNum: 2, BatchFull: 0
Index: 2, MsgNum: 2, BatchFull: 0
```
I believe this is a bit closer to the intended behavior of this function; it looks the GPU code is still not fully completely working, though. So next step would be to try to get the other functions working so that we can test the whole code path.

**Comment by cjohnson57** [comment]
Awesome, thank you for your great work. Tonight or tomorrow morning I'll test the changes and figure out the other issues.

If you'd like to make a pull request to merge your changes with my branch I think either of us can approve it

**Comment by quadpixels** [comment]
Thanks for the update! Sorry I was busy with some other stuff and had not replied for a few days.
I forgot to mention that in my changes I had created a separate DLL project just for kernel.cu so I don't have to type the command line to rebuild the .dll file, but that's just my preference.
I will help figuring out the other issues as well.

**Comment by cjohnson57** [comment]
No problem, I completely understand that you have other work to do
I actually have it set up the same way as well, I just put all the files in the same repository for convenience. 
Thank you! I have tested the code for the past couple days but haven't identified the issues yet.

**Comment by quadpixels** [comment]
It looks TDR timeout is resolved so closing this issue.
